apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagemaker
  namespace: webservice
spec:
  replicas: 1   
  selector:
    matchLabels:
      app: imagemaker
  template:
    metadata:
      labels:
        app: imagemaker
    spec:
      containers:
      - name: imagectn
        image: innnnnwoo/imagemaker:latest
        ports: 
          - containerPort: 8501
