apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef: 
    namespace: webservice
    name: db-pvc-mysql-0
  hostPath:
    path: "/str/db"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.11
    path: /str/photos

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-pv-web
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.11
    path: /str/photos
