apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef: 
    namespace: webservice
    name: db-pvc-mysql-0
  hostPath:
    path: "/str/db"
    type: DirectoryOrCreate
