apiVersion: v1
kind: Service
metadata: 
  labels: 
    io.kompose.service: db
  name: db-svc
  namespace: webservice
spec: 
  ports: 
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
    - name: cluster-udp
      port: 4567
      targetPort: 4567
      protocol: UDP
    - name: cluster-tcp
      port: 4567
      targetPort: 4567
    - name: incremental-state-transfer
      port: 4568
      targetPort: 4568
    - name: state-snapshoot
      port: 4444
      targetPort: 4444
  selector: 
    io.kompose.service: db
  type: NodePort
