apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: django-project
  name: django-project
  namespace: webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django-project
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/django-project-default: "true"
        io.kompose.service: django-project
    spec:
      containers:
        - image: innnnnwoo/jenkinshub
          name: django-project
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}

